AIO_runtime_auth=c5f3c322-4c96-4fc1-9026-e4347ef1b21b:LRpY0uNooF2K17fF2syCYD5yf7y4Bc770QfNK5Fn5G50u113E5Q8P0wGfL88dO0q
AIO_runtime_namespace=1287541-920azurerodent-rohan
AIO_runtime_apihost=https://adobeioruntime.net
AIO_ims_contexts_Credential__in__Dusk__APP__Builder__-__Rohan_client__id=bb090899c74c4a09a892b7e65f76b6e6
AIO_ims_contexts_Credential__in__Dusk__APP__Builder__-__Rohan_client__secrets=["p8e-9b0YW2OxJojwtAidqlfzrATpIwjCY7M2"]
AIO_ims_contexts_Credential__in__Dusk__APP__Builder__-__Rohan_technical__account__email=575bf334-7b18-4114-84cd-b5fd67cb7964@techacct.adobe.com
AIO_ims_contexts_Credential__in__Dusk__APP__Builder__-__Rohan_technical__account__id=09F21F6164BA058D0A495E69@techacct.adobe.com
AIO_ims_contexts_Credential__in__Dusk__APP__Builder__-__Rohan_scopes=["AdobeID","openid","read_organizations","additional_info.projectedProductContext","additional_info.roles","adobeio_api","read_client_secret","manage_client_secrets","event_receiver_api"]
AIO_ims_contexts_Credential__in__Dusk__APP__Builder__-__Rohan_ims__org__id=213A1EB76470DA4A0A495C4F@AdobeOrg
SERVICE_API_KEY=bb090899c74c4a09a892b7e65f76b6e6
SERVICE_SECRET=p8e-9b0YW2OxJojwtAidqlfzrATpIwjCY7M2
VIARE_PRODUCT_API=https://dusk.staging.viare.io/global/api/Products.asmx?WSDL
VIARE_USERNAME=duskAPI
VIARE_PASSWORD=duskAPI123
ORG_ID=213A1EB76470DA4A0A495C4F@AdobeOrg
DUSK_LOGGING_EVENT_CODE=com.dusk.logging
DUSK_MAGENTO_PROVIDER_ID=c61201af-e97c-4401-8654-250d7ec03c51
ECOMMERCE_AUTHORIZED_TOKEN=nq4zr49fhs07xv9584koqyjicyz3yybd
ECOMMERCE_API_URL=https://mcstaging.dusk.au/rest/sv_dusk_au_en/V1/
ECOMMERCE_LOGGING_ENDPOINT=addlogsinduskcommerce
ECOMMERCE_PRODUCT_ENDPOINT=products
ECOMMERCE_CUSTOMER_ENDPOINT=customers
MAGENTO_MEDIA_URL=https://mcstaging.dusk.au/media/
FUTURA_CUSTOMER_API=https://futura-staging-adr.dusk.com.au/SOAP
FUTURA_CF_ACCESS_CLIENT_ID=30979c34f222ca7ac7ac3d24120060a5.access
FUTURA_CF_ACCESS_CLIENT_SECRET=ff6e0612ff3cc2962cd1dbad55a55cf72f5d3d5f3678fdd0f3aece5f0586c048
ORDER_CREATE_EVENT_PROVIDER_ID=c61201af-e97c-4401-8654-250d7ec03c51
ORDER_CREATE_EVENT_CODE=com.magento.viarecreateorder
FUTURA_ORDER_API=https://futura-staging-host.dusk.com.au/SOAP
TEMP_ECOMMERCE_AUTHORIZED_TOKEN=u39b869kztwla5eb5jzasuh6ookp84um
TEMP_ECOMMERCE_ENDPOINT=https://mcstaging.kellyhayes.com/rest/default/V1/
ECOMMERCE_ENDPOINT=https://mcstaging.dusk.au/rest/
ECOMMERCE_ORDER_ENDPOINT=orders
VIARE_ORDER_API=https://dusk.staging.viare.io/global/api/Orders.asmx?WSDL
SOAP_TIMEOUT=20000
ECOMMERCE_PRODUCT_ATTRIBUTE_OPTIONS_ENDPOINT=products/attributes
VIARE_CLICK_COLLECT_URL=https://dusk.staging.viare.io/api/availability/store/
ECOMMERCE_ORDER_COMMENT_ENDPOINT=comments
ECOMMERCE_ORDER_SHIP_ENDPOINT=order/:orderId/ship
VIARE_ORDER_CREATE_EVENT_CODE=com.viare.ordercreate
VIARE_ORDER_CREATE_PROVIDERCODE=2e024f61-59d6-4e80-9c2c-36358b78b1ae
VIARE_ORDER_SEARCH_API=https://dusk.staging.viare.io/global/api/Orders.asmx?Search
FUTURA_ORDER_RANGE=1000000
FUTURA_AUS_DELIVERY_BRANCH=160
FUTURA_NZL_DELIVERY_BRANCH=20160
FUTURA_SHIPPING_SKU=50012848
FUTURA_AU_CODE=1
FUTURA_NZ_CODE=14
GIVEX_ENDPOINT=https://givex-betaap1-50060.tech180.com.au
GIVEX_USERID=253133
GIVEX_PASSWORD=S6uxaMUGp07NlrdL
GIVEX_LANGUAGECODE=en
FUTURA_PURCHASE_LOYALTY_SKU=50137138
FUTURA_RENEW_LOYALTY_SKU=50156788
DUSK_PORTAL_AUTH_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vc3RhZ2luZy1wb3J0YWwuZHVzay5jb20uYXUvaW5kZXgucGhwL2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjkxMTM0MjAyLCJuYmYiOjE2OTExMzQyMDIsImp0aSI6Img1NXNrZlFPamQwZ2FXU0ciLCJzdWIiOjEsInBydiI6IjYyZGFjM2UzMDg0YTcxZmJhMTMxMWQ0MDM5YzZjYTQ3MmQ0MTZmOTciLCJuYW1lIjoiYWRtaW4iLCJpc19hZG1pbiI6dHJ1ZSwiZnV0dXJhX3N0b3JlX2lkIjoiMSIsImFkbWluX3R5cGUiOjF9.A2vnXKPyrG23uf4F6x3Rary7J5KdZX_BgY9dY8eNic0
DUSK_PORTAL_API_URL=http://staging-portal.dusk.com.au/api/
DUSK_PORTAL_RESERVE_CARD_ENDPOINT=members/digital-cards/reserve-number
DUSK_PORTAL_CREATE_UPDATE_MEMBER=members/create-or-update
DUSK_PORTAL_RENEW_EXP_API=globals/renewal
GIVEX_PROVIDER_ID=ce6cc498-f707-4600-8147-bdf5444041f9
GIVEX_PURCHASE_LOYALTYMEMBER_CODE=com.givex.loyaltypurchase
GIVEX_UPDATE_LOYALTY_DATA_CODE=com.givex.loyaltyupdatedata
GIVEX_RENEW_LOYALTYMEMBER_CODE=com.givex.renewloyalty
LOYALTY_MEMBERSHIP_TIME_YEAR=2
GIVEX_GIFTCARD_CREATE_EVENTCODE=com.givex.giftcardcreate
GIVEX_GIFTCARD_CREATE_PROVIDER_ID=86e117ba-2ea2-4b5d-851f-69e04ef93729
GIVEX_LOYALTYPOINTS_PROVIDER_ID=ce6cc498-f707-4600-8147-bdf5444041f9
GIVEX_LOYALTYPOINTS_EVENTCODE=com.givex.loyaltypoints
ECOMMERCE_SHIPMENT_ENDPOINT=shipment
TCC_USERNAME=duskd2c.sigma.ws@consortiumclemenger.com.au
TCC_PASSWORD=dRbE5^66*]k}{l
TCC_ACCOUNT_ID=34468
TCC_API_URL=https://odyssey-services.tccondemand.com.au/version2.9/OMS/
TCC_AUTHENTICATION=Authenticate
TCC_ISN=ISN
ECOMMERCE_RETURNS_ENDPOINT=returns
ECOMMERCE_FUTURA_STAGE_ENDPOINT=futura/futura_id
ECOMMERCE_FUTURA_STAGE_SAVE_ENDPOINT=futura
ECOMMERCE_CUSTOMER_LOYALTY_GROUP_ID=6
ECOMMERCE_CUSTOMER_GENERAL_GROUP_ID=1
FUTURA_ADJUSTMENT_SKU=50097289
ECOMMERCE_RMA_ENDPOINT=returns